### ISSUE TITLE
GitLab login not working on wayland

### ISSUE THREAD

**Issue by pschyma** [git-ecosystem/git-credential-manager#1027]
I'm using sway and when git needs to authenticate it attempts to open a GitLab.UI window to perform the authentication. 

On wayland only a black screen is shown and the logs are flooded:
![image](https://user-images.githubusercontent.com/2489928/212465921-83654a8e-8994-4e28-9a7d-b7d0cffe7fd2.png)

```
Jan 14 10:06:16 galileo GitLab.UI[30442]: [Visual] Exception in render loop: 'System.ArgumentException: Invalid create info - no Canvas provided (Parameter 'createInfo')
                                             at Avalonia.Skia.DrawingContextImpl..ctor(CreateInfo createInfo, IDisposable[] disposables) in /_/src/Skia/Avalonia.Skia/DrawingContextImpl.cs:line 108
                                             at Avalonia.Skia.SkiaGpuRenderTarget.CreateDrawingContext(IVisualBrushRenderer visualBrushRenderer) in /_/src/Skia/Avalonia.Skia/Gpu/SkiaGpuRenderTarget.cs:line 40
                                             at Avalonia.Rendering.DeferredRenderer.EnsureDrawingContext(IDrawingContextImpl& context) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 618
                                             at Avalonia.Rendering.DeferredRenderer.UpdateRenderLayersAndConsumeSceneIfNeeded(IDrawingContextImpl& context, Boolean recursiveCall) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 416
                                             at Avalonia.Rendering.DeferredRenderer.Render(Boolean forceComposite) in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 359
                                             at Avalonia.Rendering.DeferredRenderer.Avalonia.Rendering.IRenderLoopTask.Render() in /_/src/Avalonia.Visuals/Rendering/DeferredRenderer.cs:line 277
                                             at Avalonia.Rendering.RenderLoop.TimerTick(TimeSpan time) in /_/src/Avalonia.Visuals/Rendering/RenderLoop.cs:line 147' (RenderLoop #52307948
```

It's working in a XOrg session.

This happens on terminal or in other applications (e.g. IntelliJ IDEA running on XWayland). 

GCM Version is 2.0.886.

**Comment by ldennington** [comment]
There seems to be a prevalent issue with the Avalonia UI. We're planning to update to the latest version with our next release to see if it solves this issue.

**Comment by ldennington** [comment]
This should be fixed in newer versions of GCM. If the issue persists, feel free to open a new issue.
