### ISSUE TITLE
error: fatal: Failed to open secret service session [0x13]

### ISSUE THREAD

**Issue by quinn** [git-ecosystem/git-credential-manager#1198]
### Version

2.0.935+8b4735fc7b

### Operating system

Linux

### OS version or distribution

Ubuntu 22.04

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

This stopped working suddenly. Before I could push and pull without issue.

### Actual behavior

```
fatal: Failed to open secret service session [0x13]
fatal: No such secret item at path: /org/freedesktop/secrets/collection/login/34
```

### Logs

```
07:46:29.018832 git.c:455               trace: built-in: git push
07:46:29.018933 run-command.c:668       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/....git
07:46:29.019493 git.c:742               trace: exec: git-remote-https origin https://github.com/....git
07:46:29.019511 run-command.c:668       trace: run_command: git-remote-https origin https://github.com/....git
07:46:29.129239 run-command.c:668       trace: run_command: '/home/quinn/.dotnet/tools/git-credential-manager get'
07:46:29.292212 ...re/Application.cs:95 trace: [RunInternalAsync] Version: 2.0.935.18315
07:46:29.292943 ...re/Application.cs:96 trace: [RunInternalAsync] Runtime: .NET 7.0.5
07:46:29.292963 ...re/Application.cs:97 trace: [RunInternalAsync] Platform: Linux (x86-64)
07:46:29.292967 ...re/Application.cs:98 trace: [RunInternalAsync] OSVersion: Linux quinn-desktop 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
07:46:29.292972 ...re/Application.cs:99 trace: [RunInternalAsync] AppPath: /home/quinn/.dotnet/tools/git-credential-manager
07:46:29.293013 ...e/Application.cs:100 trace: [RunInternalAsync] InstallDir: /home/quinn/.dotnet/tools/.store/git-credential-manager/2.0.935/git-credential-manager/2.0.935/tools/net6.0/any/
07:46:29.293022 ...e/Application.cs:101 trace: [RunInternalAsync] Arguments: get
07:46:29.316687 ...GitCommandBase.cs:33 trace: [ExecuteAsync] Start 'get' command...
07:46:29.322035 ...GitCommandBase.cs:47 trace: [ExecuteAsync] Detecting host provider for input:
07:46:29.322556 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   protocol=https
07:46:29.322570 ...GitCommandBase.cs:48 trace: [ExecuteAsync]   host=github.com
07:46:29.329039 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
07:46:29.330526 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
07:46:29.332779 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
07:46:29.333402 ...GitCommandBase.cs:50 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
07:46:29.334566 .../HostProvider.cs:126 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://github.com account=...
fatal: Failed to open secret service session [0x12]
   at GitCredentialManager.Interop.Linux.SecretServiceCollection.GetSecretService()
   at GitCredentialManager.Interop.Linux.SecretServiceCollection.Get(String service, String account)
   at GitCredentialManager.CredentialStore.Get(String service, String account)
   at GitCredentialManager.HostProvider.GetCredentialAsync(InputArguments input)
   at GitCredentialManager.Commands.GetCommand.ExecuteInternalAsync(InputArguments input, IHostProvider provider)
   at GitCredentialManager.Commands.GitCommandBase.ExecuteAsync()
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass3_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass26_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass24_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__23_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass10_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseExceptionHandler>b__0>d.MoveNext()
fatal: No such secret item at path: /org/freedesktop/secrets/collection/login/33

```

**Comment by joe733** [comment]
I just had the same issue. So right after shutdown and restart the first thing I did was `git push`, and it worked.

**Comment by ldennington** [comment]
> fatal: No such secret item at path: /org/freedesktop/secrets/collection/login/33

The error is coming from `libsecret`. There appears to be a problem with your setup - unfortunately this issue falls outside the scope of GCM.

**Comment by arcanemachine** [comment]
Using Ubuntu 23.04, I was able to use this command to restart the keyring daemon:

`gnome-keyring-daemon -r -d`

**Comment by excus3s** [comment]
> Using Ubuntu 23.04, I was able to use this command to restart the keyring daemon:
> 
> `gnome-keyring-daemon -r -d`
> 
> After that, everything started working again.

thanks, worked for me
