### ISSUE TITLE
Github plugin for Jenkins fails to authenticate . . . sometimes.

### ISSUE THREAD

**Issue by echristley** [git-ecosystem/git-credential-manager#1344]
### Version

2.41.0.windows.1

### Operating system

Windows

### OS version or distribution

Window 10

### Git hosting provider(s)

GitHub Enterprise Server

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

 I have a test pipeline that uses the Jenkins plugin to pull a small repo from several different machines.  IT is able to access GH most of the time, but fail on one system about 20% of the time.

### Actual behavior

One example of the failure is:

 > git --version # 'git version 2.41.0.windows.1'

using GIT_ASKPASS to set credentials GitHub Credentials for the Jenkins CPR app on ExtronGHE

> C:\Program Files\Git\bin\git.exe fetch --tags --force --progress -- https://github.com/ExtronGHE/extron-cpr-utilities +refs/heads/*:refs/remotes/origin/* # timeout=10

ERROR: Error cloning remote repo 'origin'

hudson.plugins.git.GitException: Command "C:\Program Files\Git\bin\git.exe fetch --tags --force --progress -- https://github.com/ExtronGHE/extron-cpr-utilities +refs/heads/*:refs/remotes/origin/*" returned status code 128:

stdout:

stderr: 11:56:39.554669 exec-cmd.c:243 trace: resolved executable dir: C:/Program Files/Git/mingw64/bin

11:56:39.569670 git.c:462 trace: built-in: git fetch --tags --force --progress -- https://github.com/ExtronGHE/extron-cpr-utilities '+refs/heads/*:refs/remotes/origin/*'

11:56:39.569670 read-cache.c:2451 performance: 0.000023700 s: read cache .git/index

11:56:39.571672 run-command.c:661 trace: run_command: GIT_DIR=.git git remote-https https://github.com/ExtronGHE/extron-cpr-utilities https://github.com/ExtronGHE/extron-cpr-utilities

11:56:39.590669 exec-cmd.c:243 trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core

11:56:39.592670 git.c:748 trace: exec: git-remote-https https://github.com/ExtronGHE/extron-cpr-utilities https://github.com/ExtronGHE/extron-cpr-utilities

11:56:39.592670 run-command.c:661 trace: run_command: git-remote-https https://github.com/ExtronGHE/extron-cpr-utilities https://github.com/ExtronGHE/extron-cpr-utilities

11:56:39.612669 exec-cmd.c:243 trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core

11:56:39.633678 http.c:842 == Info: Couldn't find host github.com in the (nil) file; using defaults

11:56:39.645672 http.c:842 == Info: Trying 192.30.255.112:443...

11:56:39.676675 http.c:842 == Info: Connected to github.com (192.30.255.112) port 443 (#0)

11:56:39.676675 http.c:842 == Info: ALPN: offers h2,http/1.1

11:56:39.676675 http.c:842 == Info: TLSv1.3 (OUT), TLS handshake, Client hello (1):

11:56:39.684674 http.c:842 == Info: CAfile: C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt

11:56:39.684674 http.c:842 == Info: CApath: none

11:56:39.718673 http.c:842 == Info: TLSv1.3 (IN), TLS handshake, Server hello (2):

11:56:39.718673 http.c:842 == Info: TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):

11:56:39.718673 http.c:842 == Info: TLSv1.3 (IN), TLS handshake, Certificate (11):

11:56:39.719673 http.c:842 == Info: TLSv1.3 (IN), TLS handshake, CERT verify (15):

11:56:39.720674 http.c:842 == Info: TLSv1.3 (IN), TLS handshake, Finished (20):

11:56:39.720674 http.c:842 == Info: TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):

11:56:39.720674 http.c:842 == Info: TLSv1.3 (OUT), TLS handshake, Finished (20):

11:56:39.720674 http.c:842 == Info: SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256

11:56:39.720674 http.c:842 == Info: ALPN: server accepted h2

11:56:39.720674 http.c:842 == Info: Server certificate:

11:56:39.720674 http.c:842 == Info: subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=github.com

11:56:39.720674 http.c:842 == Info: start date: Feb 14 00:00:00 2023 GMT

11:56:39.720674 http.c:842 == Info: expire date: Mar 14 23:59:59 2024 GMT

11:56:39.720674 http.c:842 == Info: subjectAltName: host "github.com" matched cert's "github.com"

11:56:39.720674 http.c:842 == Info: issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1

11:56:39.720674 http.c:842 == Info: SSL certificate verify ok.

11:56:39.720674 http.c:842 == Info: using HTTP/2

11:56:39.720674 http.c:842 == Info: h2 [:method: GET]

11:56:39.720674 http.c:842 == Info: h2 [:scheme: https]

11:56:39.720674 http.c:842 == Info: h2 [:authority: github.com]

11:56:39.720674 http.c:842 == Info: h2 [:path: /ExtronGHE/extron-cpr-utilities/info/refs?service=git-upload-pack]

11:56:39.720674 http.c:842 == Info: h2 [user-agent: git/2.41.0.windows.1]

11:56:39.720674 http.c:842 == Info: h2 [accept: */*]

11:56:39.720674 http.c:842 == Info: h2 [accept-encoding: deflate, gzip, br, zstd]

11:56:39.720674 http.c:842 == Info: h2 [pragma: no-cache]

11:56:39.720674 http.c:842 == Info: h2 [git-protocol: version=2]

11:56:39.720674 http.c:842 == Info: Using Stream ID: 1 (easy handle 0x24cc2a6ea50)

11:56:39.720674 http.c:789 => Send header, 0000000230 bytes (0x000000e6)

11:56:39.720674 http.c:801 => Send header: GET /ExtronGHE/extron-cpr-utilities/info/refs?service=git-upload-pack HTTP/2

11:56:39.720674 http.c:801 => Send header: Host: github.com

11:56:39.720674 http.c:801 => Send header: User-Agent: git/2.41.0.windows.1

11:56:39.720674 http.c:801 => Send header: Accept: */*

11:56:39.720674 http.c:801 => Send header: Accept-Encoding: deflate, gzip, br, zstd

11:56:39.720674 http.c:801 => Send header: Pragma: no-cache

11:56:39.720674 http.c:801 => Send header: Git-Protocol: version=2

11:56:39.720674 http.c:801 => Send header:

11:56:58.914289 http.c:842 == Info: Recv failure: Connection was reset

11:56:58.914289 http.c:842 == Info: OpenSSL SSL_read: Connection was reset, errno 10054

11:56:58.914289 http.c:842 == Info: Failed receiving HTTP2 data: 56(Failure when receiving data from the peer)

11:56:58.914289 http.c:842 == Info: Connection #0 to host github.com left intact

fatal: unable to access 'https://github.com/ExtronGHE/extron-cpr-utilities/': Recv failure: Connection was reset

11:56:58.918301 trace.c:415 performance: 19.325464400 s: git command: git remote-https https://github.com/ExtronGHE/extron-cpr-utilities https://github.com/ExtronGHE/extron-cpr-utilities

11:56:58.919304 trace.c:415 performance: 19.351719100 s: git command: git.exe fetch --tags --force --progress -- https://github.com/ExtronGHE/extron-cpr-utilities '+refs/heads/*:refs/remotes/origin/*'

at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2842)

at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2185)

at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:635)

at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:871)

at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:170)

at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)

at hudson.remoting.UserRequest.perform(UserRequest.java:211)

at hudson.remoting.UserRequest.perform(UserRequest.java:54)

at hudson.remoting.Request$2.run(Request.java:377)

at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)

at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:125)

at java.base/java.lang.Thread.run(Thread.java:834)

Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ANA-SWEBUILD12A.extron.com/10.113.231.1:59927

at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)

at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)

at hudson.remoting.Channel.call(Channel.java:1000)

at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:153)

at jdk.internal.reflect.GeneratedMethodAccessor826.invoke(Unknown Source)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:566)

at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:138)

at com.sun.proxy.$Proxy284.execute(Unknown Source)

at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1226)

at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1309)

at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)

at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)

at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)

at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)

at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by ldennington** [comment]
Based on the intermittency of the issue and the `connection was reset` message, this looks to be a network error. In light of that, I'm going to close this, given it is not a GCM error.
