### ISSUE TITLE
GitHub login crashes on MacOS

### ISSUE THREAD

**Issue by OperKH** [git-ecosystem/git-credential-manager#1391]
### Version

2.3.2

### Operating system

macOS

### OS version or distribution

Ventura 13.5.1

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

See a web-page where I can allow authentication on GitHub.

### Actual behavior

```console
fatal: Object reference not set to an instance of an object.
```

### Logs

```console
13:45:09.310812 git.c:749               trace: exec: git-credential-manager github login
13:45:09.311206 run-command.c:654       trace: run_command: git-credential-manager github login
13:45:09.396318 git.c:460               trace: built-in: git config --null --list
13:45:09.441062 ...e/Application.cs:106 trace: [RunInternalAsync] Version: 2.3.2.0
13:45:09.447482 ...e/Application.cs:107 trace: [RunInternalAsync] Runtime: .NET 7.0.9
13:45:09.447551 ...e/Application.cs:108 trace: [RunInternalAsync] Platform: macOS (x86-64)
13:45:09.447560 ...e/Application.cs:109 trace: [RunInternalAsync] OSVersion: 13.5.1
13:45:09.447592 ...e/Application.cs:110 trace: [RunInternalAsync] AppPath: /usr/local/bin/git-credential-manager
13:45:09.447674 ...e/Application.cs:111 trace: [RunInternalAsync] InstallDir: /usr/local/share/gcm-core/
13:45:09.447708 ...e/Application.cs:112 trace: [RunInternalAsync] Arguments: github login
13:45:09.470945 ...bHostProvider.cs:420 trace: [GetSupportedAuthenticationModesAsync] https://github.com/ is github.com - authentication schemes: 'Pat, OAuth'
13:45:09.487954 git.c:460               trace: built-in: git version
13:45:09.507512 git.c:460               trace: built-in: git config --null --type=path credential.gitHubHelper
fatal: Object reference not set to an instance of an object.
   at Avalonia.Native.WindowImpl..ctor(IAvaloniaNativeFactory factory, AvaloniaNativePlatformOptions opts, AvaloniaNativeGlPlatformGraphics glFeature) in /_/src/Avalonia.Native/WindowImpl.cs:line 34
   at Avalonia.Native.AvaloniaNativePlatform.CreateWindow() in /_/src/Avalonia.Native/AvaloniaNativePlatform.cs:line 153
   at Avalonia.Controls.Platform.PlatformManager.CreateWindow() in /_/src/Avalonia.Controls/Platform/PlatformManager.cs:line 31
   at Avalonia.Controls.Window..ctor() in /_/src/Avalonia.Controls/Window.cs:line 214
   at GitCredentialManager.UI.Controls.DialogWindow..ctor(Control view)
   at GitCredentialManager.UI.AvaloniaUi.<>c__2`1.<ShowViewAsync>b__2_0()
   at GitCredentialManager.UI.AvaloniaUi.ShowWindowInternal(Func`1 windowFunc, Object dataContext, IntPtr parentHandle, CancellationToken ct)
   at GitCredentialManager.UI.AvaloniaUi.<>c__DisplayClass6_0.<ShowWindowAsync>b__0()
   at Avalonia.Threading.JobRunner.JobWithResult`1.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 290
--- End of stack trace from previous location ---
   at GitHub.GitHubAuthentication.GetAuthenticationViaUiAsync(Uri targetUri, String userName, AuthenticationModes modes)
   at GitHub.GitHubAuthentication.GetAuthenticationAsync(Uri targetUri, String userName, AuthenticationModes modes)
   at GitHub.GitHubHostProvider.GenerateCredentialAsync(Uri remoteUri, String userName)
   at GitHub.GitHubHostProvider.AddAccountAsync(Uri url, String userName, Boolean device, Boolean browser, String token, Boolean force)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<AddMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by ldennington** [comment]
Is this something you've experienced multiple times or was it just a one-off? Also, here are a few things to try:

1. Update macOS to 13.5.2
2. Try re-installing GCM
