### ISSUE TITLE
problema de autenticación al ejecutar un comando de Git

### ISSUE THREAD

**Issue by JesicaLP84** [git-ecosystem/git-credential-manager#1430]
### Version

2.3.2

### Operating system

Windows

### OS version or distribution

Edition	Windows 11 Pro Version	22H2 Installed on	‎5/‎30/‎2023 OS build	22621.2361 Experience	Windows Feature Experience Pack 1000.22674.1000.0

### Git hosting provider(s)

Azure DevOps, GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

Lo esperado es que pueda configurar git credential-manager pero se queda asi una vez que ejecuto el comando Configuring component 'Git Credential Manager'...
Configuring component 'Azure Repos provider'....
Tambien es hacer los diferentes push origin main y que se realicen los cambios en el repositorio remoto. Los trabajos que hago en otro pc, no puedo verlos en este pc y tampoco hacer los pull para descargarmelos en este.

### Actual behavior

C:\Users\jesic\Proyecto_GITHUB\Proyecto\backend_app_beta_pidm>git credential-manager diagnose
Running diagnostics...

 [ OK ] Environment
 [ OK ] File system
 [FAIL] Networking

    [!] Encountered an exception [!]
    System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'example.com'

       at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)

       at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

       --- End of inner exception stack trace ---

       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

       at GitCredentialManager.Diagnostics.NetworkingDiagnostic.<RunInternalAsync>d__4.MoveNext()     

    --- End of stack trace from previous location where exception was thrown ---

       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

       at GitCredentialManager.Diagnostics.Diagnostic.<RunAsync>d__6.MoveNext()

    [*] Diagnostic test log [*]
    Checking networking and HTTP stack...

    Creating HTTP client... OK

    IsNetworkAvailable: True

    Sending HEAD request to http://example.com...Sending HEAD request to https://example.com... warning: HEAD request failed

    Sending HEAD request to http://httpforever.com...

 [ OK ] Git
 [ OK ] Credential storage
  >>>>  Microsoft authentication (AAD/MSA)
Unhandled Exception: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)  
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitCredentialManager.Diagnostics.NetworkingDiagnostic.<SendHttpRequest>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)     
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

### Logs

unning diagnostics...

 [ OK ] Environment
 [ OK ] File system
  >>>>  Networking
Unha[FAIL] Networking

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.HttpClient'.
   at System.Net.Http.HttpClient.CheckDisposed()
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at GitCredentialManager.HttpClientExtensions.HeadAsync(HttpClient client, Uri requestUri, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at GitCredentialManager.HttpClientExtensions.HeadAsync(HttpClient client, Uri requestUri, HttpCompletionOption completionOption)
   at GitCredentialManager.HttpClientExtensions.HeadAsync(HttpClient client, Uri requestUri)
   at GitCredentialManager.HttpClientExtensions.HeadAsync(HttpClient client, String requestUri)       
   at GitCredentialManager.Diagnostics.NetworkingDiagnostic.<SendHttpRequest>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)     
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
    [!] Encountered an exception [!]

**Comment by ldennington** [comment]
Creo que hay un problema con tu red. ¿Puedes conectarte a http://example.com desde un navegador?

**Comment by ldennington** [comment]
Closing due to lack of response.
