### ISSUE TITLE
Similar to #435, but against my private GH-repo: fatal: Interaction with the Security Server is not allowed. [0xffff9d24]

### ISSUE THREAD

**Issue by jby** [git-ecosystem/git-credential-manager#1500]
### Version

2.4.1

### Operating system

macOS

### OS version or distribution

Sonoma 14.1

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

I'm not entirely sure what the proper behaviour is

### Actual behavior

```
git pull
Select an authentication method for 'https://github.com/':
  1. Device code (default)
  2. Personal access token
option (enter for default):
To complete authentication please visit https://github.com/login/device and enter the following code:
AA16-C06A
fatal: Interaction with the Security Server is not allowed. [0xffff9d24]
Already up to date.
```

### Logs

```
WSLENV=$WSLENV:GCM_TRACE:GIT_TRACE GCM_TRACE=1 GIT_TRACE=1 git fetch
15:08:43.708820 git.c:463               trace: built-in: git fetch
15:08:43.709891 run-command.c:659       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/jby/myconfig.git
15:08:43.720030 git.c:749               trace: exec: git-remote-https origin https://github.com/jby/myconfig.git
15:08:43.720331 run-command.c:659       trace: run_command: git-remote-https origin https://github.com/jby/myconfig.git
15:08:43.915988 run-command.c:659       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager get'
15:08:44.000606 git.c:463               trace: built-in: git config --null --list
15:08:44.059138 ...e/Application.cs:106 trace: [RunInternalAsync] Version: 2.4.1.0
15:08:44.060168 ...e/Application.cs:107 trace: [RunInternalAsync] Runtime: .NET 7.0.13
15:08:44.060213 ...e/Application.cs:108 trace: [RunInternalAsync] Platform: macOS (x86-64)
15:08:44.060219 ...e/Application.cs:109 trace: [RunInternalAsync] OSVersion: 14.1.0
15:08:44.060249 ...e/Application.cs:110 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager
15:08:44.060322 ...e/Application.cs:111 trace: [RunInternalAsync] InstallDir: /usr/local/share/gcm-core/
15:08:44.060351 ...e/Application.cs:112 trace: [RunInternalAsync] Arguments: get
15:08:44.082157 ...GitCommandBase.cs:32 trace: [ExecuteAsync] Start 'get' command...
15:08:44.090411 ...GitCommandBase.cs:46 trace: [ExecuteAsync] Detecting host provider for input:
15:08:44.091801 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   protocol=https
15:08:44.091860 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   host=github.com
15:08:44.091871 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   wwwauth=Basic realm="GitHub"
15:08:44.095719 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
15:08:44.096010 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
15:08:44.099102 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
15:08:44.100806 ...GitCommandBase.cs:49 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
15:08:44.119112 ...bHostProvider.cs:142 trace: [GetCredentialAsync] Found 0 accounts in the store for service=https://github.com.
15:08:44.119979 ...bHostProvider.cs:218 trace: [FilterAccounts] Account filtering is enabled.
15:08:44.135351 ...bHostProvider.cs:226 trace: [FilterAccounts] Filtering based on WWW-Authenticate header information...
15:08:44.135776 ...bHostProvider.cs:229 trace: [FilterAccounts] Matched 0 accounts with public domain:
15:08:44.135794 ...bHostProvider.cs:181 trace: [GetCredentialAsync] No existing credentials found.
15:08:44.135799 ...bHostProvider.cs:184 trace: [GetCredentialAsync] Creating new credential...
15:08:44.138230 ...bHostProvider.cs:420 trace: [GetSupportedAuthenticationModesAsync] https://github.com/ is github.com - authentication schemes: 'Pat, OAuth'
Select an authentication method for 'https://github.com/':
  1. Device code (default)
  2. Personal access token
option (enter for default): 15:08:44.145112 .../MacOSTerminal.cs:45 trace: [.ctor] Setting terminal echo state to 'True'

15:08:52.835228 ...pClientFactory.cs:60 trace: [CreateClient] Creating new HTTP client instance...
15:08:52.838725 ...pClientFactory.cs:80 trace: [CreateClient] Git's SSL/TLS backend is: OpenSsl
15:08:52.854412 git.c:463               trace: built-in: git version
15:08:52.873143 git.c:463               trace: built-in: git config --null --type=path http.https://github.com.sslCAInfo
15:08:52.887511 git.c:463               trace: built-in: git config --null --type=path http.github.com.sslCAInfo
15:08:52.901423 git.c:463               trace: built-in: git config --null --type=path http.sslCAInfo
15:08:52.915929 git.c:463               trace: built-in: git config --null --type=path http.https://github.com.cookieFile
15:08:52.928495 git.c:463               trace: built-in: git config --null --type=path http.github.com.cookieFile
15:08:52.941207 git.c:463               trace: built-in: git config --null --type=path http.cookieFile
To complete authentication please visit https://github.com/login/device and enter the following code:
F6B0-B4A8
15:09:14.096825 .../GitHubRestApi.cs:96 trace: [GetUserInfoAsync] HTTP: GET https://api.github.com/user
15:09:14.097242 ...pClientFactory.cs:60 trace: [CreateClient] Creating new HTTP client instance...
15:09:14.097360 ...pClientFactory.cs:80 trace: [CreateClient] Git's SSL/TLS backend is: OpenSsl
15:09:14.112491 git.c:463               trace: built-in: git config --null --type=path http.https://github.com.sslCAInfo
15:09:14.126335 git.c:463               trace: built-in: git config --null --type=path http.github.com.sslCAInfo
15:09:14.139830 git.c:463               trace: built-in: git config --null --type=path http.sslCAInfo
15:09:14.153363 git.c:463               trace: built-in: git config --null --type=path http.https://github.com.cookieFile
15:09:14.167078 git.c:463               trace: built-in: git config --null --type=path http.github.com.cookieFile
15:09:14.180260 git.c:463               trace: built-in: git config --null --type=path http.cookieFile
15:09:14.513103 ...GitHubRestApi.cs:103 trace: [GetUserInfoAsync] HTTP: Response 200 [OK]
15:09:14.516297 ...bHostProvider.cs:186 trace: [GetCredentialAsync] Credential created.
15:09:14.516506 ...nds/GetCommand.cs:39 trace: [ExecuteInternalAsync] Writing credentials to output:
15:09:14.516656 ...nds/GetCommand.cs:40 trace: [ExecuteInternalAsync]   protocol=https
15:09:14.516690 ...nds/GetCommand.cs:40 trace: [ExecuteInternalAsync]   host=github.com
15:09:14.516706 ...nds/GetCommand.cs:40 trace: [ExecuteInternalAsync]   username=jby
15:09:14.516771 ...nds/GetCommand.cs:40 trace: [ExecuteInternalAsync]   password=********
15:09:14.517242 ...GitCommandBase.cs:53 trace: [ExecuteAsync] End 'get' command...
15:09:14.789711 run-command.c:659       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager store'
15:09:14.873108 git.c:463               trace: built-in: git config --null --list
15:09:14.931632 ...e/Application.cs:106 trace: [RunInternalAsync] Version: 2.4.1.0
15:09:14.932657 ...e/Application.cs:107 trace: [RunInternalAsync] Runtime: .NET 7.0.13
15:09:14.932702 ...e/Application.cs:108 trace: [RunInternalAsync] Platform: macOS (x86-64)
15:09:14.932708 ...e/Application.cs:109 trace: [RunInternalAsync] OSVersion: 14.1.0
15:09:14.932738 ...e/Application.cs:110 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager
15:09:14.932809 ...e/Application.cs:111 trace: [RunInternalAsync] InstallDir: /usr/local/share/gcm-core/
15:09:14.932838 ...e/Application.cs:112 trace: [RunInternalAsync] Arguments: store
15:09:14.954485 ...GitCommandBase.cs:32 trace: [ExecuteAsync] Start 'store' command...
15:09:14.962862 ...GitCommandBase.cs:46 trace: [ExecuteAsync] Detecting host provider for input:
15:09:14.964410 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   protocol=https
15:09:14.964563 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   host=github.com
15:09:14.964584 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   username=jby
15:09:14.964645 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   password=********
15:09:14.968866 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
15:09:14.969140 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
15:09:14.972321 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
15:09:14.974009 ...GitCommandBase.cs:49 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
15:09:14.974674 ...bHostProvider.cs:257 trace: [StoreCredentialAsync] Storing credential with service=https://github.com account=jby...
fatal: Interaction with the Security Server is not allowed. [0xffff9d24]
   at GitCredentialManager.Interop.MacOS.Native.SecurityFramework.ThrowIfError(Int32 error, String defaultErrorMessage)
   at GitCredentialManager.Interop.MacOS.MacOSKeychain.AddOrUpdate(String service, String account, String secret)
   at GitCredentialManager.CredentialStore.AddOrUpdate(String service, String account, String secret)
   at GitHub.GitHubHostProvider.StoreCredentialAsync(InputArguments input)
   at GitCredentialManager.Commands.StoreCommand.ExecuteInternalAsync(InputArguments input, IHostProvider provider)
   at GitCredentialManager.Commands.GitCommandBase.ExecuteAsync()
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<AddMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
15:09:15.243583 run-command.c:659       trace: run_command: git rev-list --objects --stdin --not --exclude-hidden=fetch --all --quiet --alternate-refs
15:09:15.262817 run-command.c:1524      run_processes_parallel: preparing to run up to 1 tasks
15:09:15.262834 run-command.c:1551      run_processes_parallel: done
15:09:15.262845 run-command.c:659       trace: run_command: git maintenance run --auto --no-quiet
15:09:15.273842 git.c:463               trace: built-in: git maintenance run --auto --no-quiet

```

**Comment by jby** [comment]
[gcm-diagnose.log](https://github.com/git-ecosystem/git-credential-manager/files/13779374/gcm-diagnose.log)

**Comment by jby** [comment]
I'm now seing this on a newly installed Apple Silicon based Mac...

**Comment by jby** [comment]
WSLENV=$WSLENV:GCM_TRACE:GIT_TRACE GCM_TRACE=1 GIT_TRACE=1 git fetch
15:53:46.232470 git.c:463               trace: built-in: git fetch
15:53:46.233910 run-command.c:657       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/jby/myconfig.git
15:53:46.245707 git.c:750               trace: exec: git-remote-https origin https://github.com/jby/myconfig.git
15:53:46.245986 run-command.c:657       trace: run_command: git-remote-https origin https://github.com/jby/myconfig.git
15:53:46.447084 run-command.c:657       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager get'
15:53:46.540689 git.c:463               trace: built-in: git config --null --list
15:53:46.570020 ...e/Application.cs:106 trace: [RunInternalAsync] Version: 2.5.0.0
15:53:46.571702 ...e/Application.cs:107 trace: [RunInternalAsync] Runtime: .NET 8.0.4
15:53:46.571711 ...e/Application.cs:108 trace: [RunInternalAsync] Platform: macOS (ARM64)
15:53:46.571714 ...e/Application.cs:109 trace: [RunInternalAsync] OSVersion: 14.4.1
15:53:46.571721 ...e/Application.cs:110 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager
15:53:46.571742 ...e/Application.cs:111 trace: [RunInternalAsync] InstallDir: /usr/local/share/gcm-core/
15:53:46.571756 ...e/Application.cs:112 trace: [RunInternalAsync] Arguments: get
15:53:46.581222 ...GitCommandBase.cs:32 trace: [ExecuteAsync] Start 'get' command...
15:53:46.584621 ...GitCommandBase.cs:46 trace: [ExecuteAsync] Detecting host provider for input:
15:53:46.585209 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   protocol=https
15:53:46.585229 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   host=github.com
15:53:46.585233 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   wwwauth=Basic realm="GitHub"
15:53:46.587208 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
15:53:46.588236 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
15:53:46.590200 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
15:53:46.590917 ...GitCommandBase.cs:49 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
15:53:46.600515 ...bHostProvider.cs:142 trace: [GetCredentialAsync] Found 0 accounts in the store for service=https://github.com.
15:53:46.600976 ...bHostProvider.cs:218 trace: [FilterAccounts] Account filtering is enabled.
15:53:46.606908 ...bHostProvider.cs:226 trace: [FilterAccounts] Filtering based on WWW-Authenticate header information...
15:53:46.607026 ...bHostProvider.cs:229 trace: [FilterAccounts] Matched 0 accounts with public domain:
15:53:46.607037 ...bHostProvider.cs:181 trace: [GetCredentialAsync] No existing credentials found.
15:53:46.607040 ...bHostProvider.cs:184 trace: [GetCredentialAsync] Creating new credential...
15:53:46.608710 ...bHostProvider.cs:420 trace: [GetSupportedAuthenticationModesAsync] https://github.com/ is github.com - authentication schemes: 'Pat, OAuth'
Select an authentication method for 'https://github.com/':
  1. Device code (default)
  2. Personal access token
option (enter for default): 15:53:46.611821 .../MacOSTerminal.cs:45 trace: [.ctor] Setting terminal echo state to 'True'

15:53:49.399675 ...pClientFactory.cs:60 trace: [CreateClient] Creating new HTTP client instance...
15:53:49.409825 ...pClientFactory.cs:80 trace: [CreateClient] Git's SSL/TLS backend is: OpenSsl
15:53:49.452827 git.c:463               trace: built-in: git version
15:53:49.481626 git.c:463               trace: built-in: git config --null --type=path http.https://github.com.sslCAInfo
15:53:49.498219 git.c:463               trace: built-in: git config --null --type=path http.github.com.sslCAInfo
15:53:49.513701 git.c:463               trace: built-in: git config --null --type=path http.sslCAInfo
15:53:49.529396 git.c:463               trace: built-in: git config --null --type=path http.https://github.com.cookieFile
15:53:49.544952 git.c:463               trace: built-in: git config --null --type=path http.github.com.cookieFile
15:53:49.560544 git.c:463               trace: built-in: git config --null --type=path http.cookieFile
To complete authentication please visit https://github.com/login/device and enter the following code:
2B7C-738B
15:54:05.592481 .../GitHubRestApi.cs:96 trace: [GetUserInfoAsync] HTTP: GET https://api.github.com/user
15:54:05.593497 ...pClientFactory.cs:60 trace: [CreateClient] Creating new HTTP client instance...
15:54:05.593728 ...pClientFactory.cs:80 trace: [CreateClient] Git's SSL/TLS backend is: OpenSsl
15:54:05.644136 git.c:463               trace: built-in: git config --null --type=path http.https://github.com.sslCAInfo
15:54:05.672132 git.c:463               trace: built-in: git config --null --type=path http.github.com.sslCAInfo
15:54:05.691028 git.c:463               trace: built-in: git config --null --type=path http.sslCAInfo
15:54:05.707421 git.c:463               trace: built-in: git config --null --type=path http.https://github.com.cookieFile
15:54:05.723614 git.c:463               trace: built-in: git config --null --type=path http.github.com.cookieFile
15:54:05.739826 git.c:463               trace: built-in: git config --null --type=path http.cookieFile
15:54:06.060250 ...GitHubRestApi.cs:103 trace: [GetUserInfoAsync] HTTP: Response 200 [OK]
15:54:06.063632 ...bHostProvider.cs:186 trace: [GetCredentialAsync] Credential created.
15:54:06.063778 ...nds/GetCommand.cs:39 trace: [ExecuteInternalAsync] Writing credentials to output:
15:54:06.063855 ...nds/GetCommand.cs:40 trace: [ExecuteInternalAsync]   protocol=https
15:54:06.063867 ...nds/GetCommand.cs:40 trace: [ExecuteInternalAsync]   host=github.com
15:54:06.063883 ...nds/GetCommand.cs:40 trace: [ExecuteInternalAsync]   username=jby
15:54:06.063926 ...nds/GetCommand.cs:40 trace: [ExecuteInternalAsync]   password=********
15:54:06.064370 ...GitCommandBase.cs:53 trace: [ExecuteAsync] End 'get' command...
15:54:06.279187 run-command.c:657       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager store'
15:54:06.377534 git.c:463               trace: built-in: git config --null --list
15:54:06.406880 ...e/Application.cs:106 trace: [RunInternalAsync] Version: 2.5.0.0
15:54:06.408570 ...e/Application.cs:107 trace: [RunInternalAsync] Runtime: .NET 8.0.4
15:54:06.408579 ...e/Application.cs:108 trace: [RunInternalAsync] Platform: macOS (ARM64)
15:54:06.408582 ...e/Application.cs:109 trace: [RunInternalAsync] OSVersion: 14.4.1
15:54:06.408590 ...e/Application.cs:110 trace: [RunInternalAsync] AppPath: /usr/local/share/gcm-core/git-credential-manager
15:54:06.408612 ...e/Application.cs:111 trace: [RunInternalAsync] InstallDir: /usr/local/share/gcm-core/
15:54:06.408625 ...e/Application.cs:112 trace: [RunInternalAsync] Arguments: store
15:54:06.418102 ...GitCommandBase.cs:32 trace: [ExecuteAsync] Start 'store' command...
15:54:06.421603 ...GitCommandBase.cs:46 trace: [ExecuteAsync] Detecting host provider for input:
15:54:06.422158 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   protocol=https
15:54:06.422171 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   host=github.com
15:54:06.422175 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   username=jby
15:54:06.422197 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   password=********
15:54:06.424120 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
15:54:06.425130 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
15:54:06.427056 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
15:54:06.427737 ...GitCommandBase.cs:49 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
15:54:06.428019 ...bHostProvider.cs:257 trace: [StoreCredentialAsync] Storing credential with service=https://github.com account=jby...
fatal: Interaction with the Security Server is not allowed. [0xffff9d24]
   at GitCredentialManager.Interop.MacOS.Native.SecurityFramework.ThrowIfError(Int32 error, String defaultErrorMessage)
   at GitCredentialManager.Interop.MacOS.MacOSKeychain.AddOrUpdate(String service, String account, String secret)
   at GitCredentialManager.CredentialStore.AddOrUpdate(String service, String account, String secret)
   at GitHub.GitHubHostProvider.StoreCredentialAsync(InputArguments input)
   at GitCredentialManager.Commands.StoreCommand.ExecuteInternalAsync(InputArguments input, IHostProvider provider)
   at GitCredentialManager.Commands.GitCommandBase.ExecuteAsync()
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<AddMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
15:54:06.704920 run-command.c:657       trace: run_command: git rev-list --objects --stdin --not --exclude-hidden=fetch --all --quiet --alternate-refs
15:54:06.740217 run-command.c:1522      run_processes_parallel: preparing to run up to 1 tasks
15:54:06.740251 run-command.c:1549      run_processes_parallel: done
15:54:06.740262 run-command.c:657       trace: run_command: git maintenance run --auto --no-quiet
15:54:06.753590 git.c:463               trace: built-in: git maintenance run --auto --no-quiet

**Comment by jby** [comment]
[gcm-diagnose.log](https://github.com/git-ecosystem/git-credential-manager/files/15150184/gcm-diagnose.log)

**Comment by jby** [comment]
I solved both by applying the "fix" from https://github.com/sparkle-project/Sparkle/issues/1323:

```
security unlock-keychain -p "$pa55w0rd" /Users/$USER/Library/Keychains/login.keychain
```
