### ISSUE TITLE
XOpenDisplay failed when  running on WSL 2.2

### ISSUE THREAD

**Issue by mikelor** [git-ecosystem/git-credential-manager#1592]
### Version

2.4.1

### Operating system

Linux

### OS version or distribution

Ubuntu 22.04.4 LTS / WSL 2.2.2.0 

### Git hosting provider(s)

GitHub

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

When doing a git push I would expect the Github authentication popup in XWindows

This was working fine **until** I upgraded to WSL 2.2.2 from WSL 2.1.5.0 to fix this issue https://twitter.com/mikelor/status/1780657187649654992

### Actual behavior

```
 ~/repos/tsathroughput   main  git push
Unhandled exception. System.Exception: XOpenDisplay failed
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options)
   at Avalonia.AvaloniaX11PlatformExtensions.<>c.<UseX11>b__0_0()
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithoutStarting()
   at GitCredentialManager.UI.AvaloniaUi.<>c__DisplayClass8_1.<ShowWindowAsync>b__1(CancellationToken appCancelToken)
   at GitCredentialManager.UI.Dispatcher.DispatcherJob.Execute(CancellationToken ct)
   at GitCredentialManager.UI.Dispatcher.DispatcherJobQueue.Run()
   at GitCredentialManager.UI.Dispatcher.Run()
   at GitCredentialManager.Program.Main(String[] args)
Aborted
Username for 'https://github.com': ^C
```

**Comment by mjcheetham** [comment]
> This was working fine until I upgraded to WSL 2.2.2 from WSL 2.1.5.0

This indicates a regression and issue with WSL. Please reach out to the Windows or WSL teams.

**Comment by mikelor** [comment]
So after much searching I found out that the issue is related to some changes in WSL 2.2+ relating to how they handle WSL Networking. You can read all about it here. https://github.com/microsoft/WSL/issues/11698#issuecomment-2176996205 

After configuring with the recommended export, all of my Avalonia Apps work. Strange that this did not affect XEyes, GCalculator and other non Avalonia Based Apps.

export DISPLAY=$(ip route | grep default | awk '{print $3}'):0.0
