### ISSUE TITLE
wsl: Unable to find git.exe

### ISSUE THREAD

**Issue by simra** [git-ecosystem/git-credential-manager#1643]
I installed git for Windows and in wsl configured the windows git-credential-manager:
`credential.helper=/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager.exe`

When I try to use the credential helper it claims it can't find git.exe.  I have updated my .bashrc, .profile, set a local environment variable and it consistently fails:
```
$ /mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager.exe

Unhandled Exception: System.Exception: Failed to locate 'git.exe' executable on the path.
   at GitCredentialManager.EnvironmentExtensions.LocateExecutable(IEnvironment environment, String program)
   at GitCredentialManager.CommandContext.GetGitPath(IEnvironment environment, IFileSystem fileSystem, ITrace trace)
   at GitCredentialManager.CommandContext..ctor()
   at GitCredentialManager.Program.AppMain(Object o)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

```
$ which git.exe
/mnt/c/Program Files/Git/bin/git.exe
```

Do I need to do something special in the windows environment to pick it up?

**Comment by simra** [comment]
The issue seems to be because the Windows Git environment variables aren't picked up until after signing out and signing back in. It may be worth adding to the documentation that this is necessary. I'll go ahead and close the issue.

**Comment by dscho** [comment]
I had to modify my `WSLENV` environment variable to make it work, IIRC:

```console
$ echo $WSLENV
WT_SESSION:WT_PROFILE_ID:WT_SESSION::WT_PROFILE_ID:GIT_EXEC_PATH/wp
```
