### ISSUE TITLE
Arch Linux Missing Dependencies

### ISSUE THREAD

**Issue by lolpro11** [git-ecosystem/git-credential-manager#1707]
```/usr/lib/share/git-credential-manager/libHarfBuzzSharp.so: cannot open shared object file: No such file or directory
/usr/lib/share/git-credential-manager/liblibHarfBuzzSharp.so: cannot open shared object file: No such file or directory
/usr/lib/share/git-credential-manager/libHarfBuzzSharp: cannot open shared object file: No such file or directory
/usr/lib/share/git-credential-manager/liblibHarfBuzzSharp: cannot open shared object file: No such file or directory
```
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/lib/share/git-credential-manager/libSkiaSharp.so: cannot open shared object file: No such file or directory
/usr/lib/share/git-credential-manager/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/usr/lib/share/git-credential-manager/libSkiaSharp: cannot open shared object file: No such file or directory
/usr/lib/share/git-credential-manager/liblibSkiaSharp: cannot open shared object file: No such file or directory

   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at Avalonia.Skia.PlatformRenderInterface..ctor(Nullable`1 maxResourceBytes)
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options)
   at Avalonia.SkiaApplicationExtensions.<>c.<UseSkia>b__0_0()
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithoutStarting()
   at GitCredentialManager.UI.AvaloniaUi.<>c__DisplayClass8_1.<ShowWindowAsync>b__1(CancellationToken appCancelToken)
   at GitCredentialManager.UI.Dispatcher.DispatcherJob.Execute(CancellationToken ct)
   at GitCredentialManager.UI.Dispatcher.DispatcherJobQueue.Run()
   at GitCredentialManager.UI.Dispatcher.Run()
   at GitCredentialManager.Program.Main(String[] args)
error: git-credential-manager died of signal 6
```
This happens in Arch Linux. Could you guys update the dependencies list in the AUR to include skia-sharp-2.88.8-1?
Thanks.

**Comment by paolomainardi** [comment]
Same issue.

**Comment by dscho** [comment]
>  Could you guys update the dependencies list in the AUR to include skia-sharp-2.88.8-1?

How would you do that? Could you demonstrate, preferably in a PR?

**Comment by oliveiraop** [comment]
The linux tarball comes with two extra files libHarfBuzzSharp.so and libSkiaSharp.so.
I resolved the issue copying these to /usr/lib/share/git-credential-manager folder alongside the installed binaries via AUR.

**Comment by Dracrius** [comment]
I wish someone would fix this it's such a simple fix but bugger did it take me to long to find this issue for the solution. Thanks @oliveiraop

**Comment by ilkka** [comment]
I was confused by this also and first did the workaround, but it turns out the libs are split into a separate AUR package called git-credential-manager-extras, see this comment by the  maintainer: https://aur.archlinux.org/packages/git-credential-manager#comment-1017287
