### ISSUE TITLE
Git pull fails on Argument_CultureNotSupported

### ISSUE THREAD

**Issue by Tranquility2** [git-ecosystem/git-credential-manager#1787]
### Version

2.6.0+3c28096588f549cb46f36b552390514356830abe

### Operating system

macOS

### OS version or distribution

Sonoma 14.7.1

### Git hosting provider(s)

Azure DevOps

### (Azure DevOps only) What format is your remote URL?

https://{org}.visualstudio.com

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

Git 'pull' should be working

### Actual behavior

Using `LANG=en_US:UTF-8` (in this specific example, as a env var) while system local is different will results in:  
 
```Process terminated. Encountered infinite recursion while looking up resource 'Argument_CultureNotSupported' in System.Private.CoreLib. Verify the installation of .NET is complete and does not need repairing, and that the state of the process has not become corrupted. ```

### Logs

```bash
#git pull
Process terminated. Encountered infinite recursion while looking up resource 'Argument_CultureNotSupported' in System.Private.CoreLib. Verify the installation of .NET is complete and does not need repairing, and that the state of the process has not become corrupted.
   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String)
   at System.Globalization.CultureInfo..ctor(System.String, Boolean)
   at System.Globalization.CultureInfo.GetCultureByName(System.String)
   at System.Globalization.CultureInfo.GetUserDefaultCulture()
   at System.Globalization.CultureInfo.InitializeUserDefaultCulture()
   at System.Globalization.CultureInfo.InitializeUserDefaultUICulture()
   at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String)
   at System.Globalization.CultureInfo..ctor(System.String, Boolean)
   at System.Globalization.CultureInfo.GetCultureByName(System.String)
   at System.Globalization.CultureInfo.GetUserDefaultCulture()
   at System.Globalization.CultureInfo.InitializeUserDefaultCulture()
   at System.Globalization.CultureInfo.InitializeUserDefaultUICulture()
   at System.TimeZoneInfo.GetUtcStandardDisplayName()
   at System.TimeZoneInfo.CreateUtcTimeZone()
   at System.TimeZoneInfo..cctor()
   at System.DateTime.get_Now()
   at System.Diagnostics.ProcessWaitState.SetExited()
   at System.Diagnostics.ProcessWaitState.ChildReaped(Int32, Boolean)
   at System.Diagnostics.ProcessWaitState.TryReapChild(Boolean)
   at System.Diagnostics.ProcessWaitState.CheckChildren(Boolean, Boolean)
   at System.Diagnostics.Process.OnSigChild(Int32, Int32)
error: /usr/local/share/gcm-core/git-credential-manager get died of signal 6
```

```bash
#defaults read .GlobalPreferences AppleLanguages
(
    "en-IL",
    "he-IL"
)
```

```bash
#locale
LANG="en_US:UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

> [!NOTE] 
>` git credential-manager diagnose` crashes exactly the same without printing any other info

**Comment by mjcheetham** [comment]
Doing some reading, it may be that the required separator for UTF-8 would be `.` and not `:`?

For example `LANG="en_US.UTF-8"`

**Comment by mjcheetham** [comment]
In fact, running `locale` on my system shows the following:

```console
% locale
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
```

I haven't made any other customisations from the default macOS install, after having selected "English (United Kingdom)" when I first set up my Mac.

**Comment by Tranquility2** [comment]
amazing catch @mjcheetham, thank you.
The LANG string was the issue as you suggested, it just failed on its parsing :)
