### ISSUE TITLE
GitLab authentication no longer working

### ISSUE THREAD

**Issue by dosolkowski-work** [git-ecosystem/git-credential-manager#1796]
### Version

2.6.0+3c28096588f549cb46f36b552390514356830abe

### Operating system

Windows

### OS version or distribution

Windows 11 Pro 23H2 x64

### Git hosting provider(s)

GitLab

### (Azure DevOps only) What format is your remote URL?

None

### Can you access the remote repository directly in the browser?

Yes, I can access the repository

### Expected behavior

Git Credential Manager is able to authenticate in the browser.

### Actual behavior

GitLab thinks everything has authenticated fine but Git Credential Manager crashes with a fatal error.

I see a supposed success screen:
![image](https://github.com/user-attachments/assets/5e6ecb79-9687-4bb5-8af3-d5b3d02fdd3a)

But receive a fatal error and Git operations do not succeed.

### Logs

```
$ git pull
13:02:22.569557 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
13:02:22.576572 git.c:479               trace: built-in: git pull
13:02:22.577569 run-command.c:667       trace: run_command: git fetch --update-head-ok
13:02:22.577569 run-command.c:928       trace: start_command: git fetch --update-head-ok
13:02:22.596372 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:22.597384 git.c:479               trace: built-in: git fetch --update-head-ok
13:02:22.601993 run-command.c:667       trace: run_command: GIT_DIR=.git git remote-https origin https://gitlab.com/path/to/repo.git
13:02:22.601993 run-command.c:928       trace: start_command: git remote-https origin https://gitlab.com/path/to/repo.git
13:02:22.620868 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:22.621962 git.c:783               trace: exec: git-remote-https origin https://gitlab.com/path/to/repo.git
13:02:22.621962 run-command.c:667       trace: run_command: git-remote-https origin https://gitlab.com/path/to/repo.git
13:02:22.621962 run-command.c:928       trace: start_command: git-remote-https origin https://gitlab.com/path/to/repo.git
13:02:22.641950 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:23.117922 run-command.c:667       trace: run_command: 'git credential-manager get'
13:02:23.117922 run-command.c:928       trace: start_command: 'C:/Program Files/Git/usr/bin/sh.exe' -c 'git credential-manager get' 'git credential-manager get'
13:02:23.420438 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:23.421466 git.c:783               trace: exec: git-credential-manager get
13:02:23.421466 run-command.c:667       trace: run_command: git-credential-manager get
13:02:23.421466 run-command.c:928       trace: start_command: git-credential-manager get
13:02:23.495310 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:23.495310 git.c:479               trace: built-in: git config --null --list
13:02:23.533375 ...\Application.cs:106  trace: [RunInternalAsync] Version: 2.6.0.0
13:02:23.533375 ...\Application.cs:107  trace: [RunInternalAsync] Runtime: .NET Framework 4.8.9256.0
13:02:23.533375 ...\Application.cs:108  trace: [RunInternalAsync] Platform: Windows (x86-64)
13:02:23.533375 ...\Application.cs:109  trace: [RunInternalAsync] OSVersion: 10.0 (build 22631)
13:02:23.534371 ...\Application.cs:110  trace: [RunInternalAsync] AppPath: C:\Program Files\Git\mingw64\bin\git-credential-manager.exe
13:02:23.534371 ...\Application.cs:111  trace: [RunInternalAsync] InstallDir: C:\Program Files\Git\mingw64\bin\
13:02:23.534371 ...\Application.cs:112  trace: [RunInternalAsync] Arguments: get
13:02:23.555341 ...GitCommandBase.cs:32 trace: [ExecuteAsync] Start 'get' command...
13:02:23.562311 ...GitCommandBase.cs:46 trace: [ExecuteAsync] Detecting host provider for input:
13:02:23.564366 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   capability[]=authtype
13:02:23.564366 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   capability[]=state
13:02:23.564366 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   protocol=https
13:02:23.564366 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   host=gitlab.com
13:02:23.564366 ...GitCommandBase.cs:47 trace: [ExecuteAsync]   wwwauth=Basic realm="GitLab"
13:02:23.566314 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
13:02:23.567395 ...viderRegistry.cs:162 trace: [GetProviderAsync] Auto-detect probe timeout is 2 ms.
13:02:23.568201 ...viderRegistry.cs:170 trace: [GetProviderAsync] Checking against 4 host providers registered with priority 'Normal'.
13:02:23.568808 ...GitCommandBase.cs:49 trace: [ExecuteAsync] Host provider 'GitLab' was selected.
13:02:23.594956 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:23.594956 git.c:479               trace: built-in: git version
13:02:23.617416 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:23.617416 git.c:479               trace: built-in: git config --null --type=path credential.https://gitlab.com.gitLabHelper
13:02:23.639329 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:23.640328 git.c:479               trace: built-in: git config --null --type=path credential.gitlab.com.gitLabHelper
13:02:23.660062 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:23.661064 git.c:479               trace: built-in: git config --null --type=path credential.gitLabHelper
13:02:29.426258 ...pClientFactory.cs:60 trace: [CreateClient] Creating new HTTP client instance...
13:02:29.445021 ...pClientFactory.cs:80 trace: [CreateClient] Git's SSL/TLS backend is: OpenSsl
13:02:29.461791 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:29.463520 git.c:479               trace: built-in: git config --null --type=path http.https://gitlab.com.sslCAInfo
13:02:29.483378 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:29.484378 git.c:479               trace: built-in: git config --null --type=path http.gitlab.com.sslCAInfo
13:02:29.504378 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:29.505378 git.c:479               trace: built-in: git config --null --type=path http.sslCAInfo
13:02:29.526377 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:29.527377 git.c:479               trace: built-in: git config --null --type=path http.https://gitlab.com.sslCAInfo
13:02:29.545377 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:29.546378 git.c:479               trace: built-in: git config --null --type=path http.gitlab.com.sslCAInfo
13:02:29.566377 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:29.567377 git.c:479               trace: built-in: git config --null --type=path http.sslCAInfo
13:02:29.569378 ...ClientFactory.cs:113 trace: [CreateClient] Custom certificate verification has been enabled with certificate bundle at C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
13:02:29.587898 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:29.588898 git.c:479               trace: built-in: git config --null --type=path http.https://gitlab.com.cookieFile
13:02:29.613898 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:29.614899 git.c:479               trace: built-in: git config --null --type=path http.gitlab.com.cookieFile
13:02:29.634899 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
13:02:29.635898 git.c:479               trace: built-in: git config --null --type=path http.cookieFile
info: please complete authentication in your browser...
fatal: invalid_grant: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
   at GitCredentialManager.Authentication.OAuth.OAuth2Client.<GetTokenByAuthorizationCodeAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitLab.GitLabAuthentication.<GetOAuthTokenViaBrowserAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitLab.GitLabHostProvider.<GenerateOAuthCredentialAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitLab.GitLabHostProvider.<GenerateCredentialAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitLab.GitLabHostProvider.<GetCredentialAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GitCredentialManager.Commands.GetCommand.<ExecuteInternalAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GitCredentialManager.Commands.GitCommandBase.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.AnonymousCommandHandler.<InvokeAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<AddMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
13:02:33.084097 run-command.c:667       trace: run_command: bash -c 'cat >/dev/tty && read -r line </dev/tty && echo "$line"'
13:02:33.084097 run-command.c:928       trace: start_command: bash -c 'cat >/dev/tty && read -r line </dev/tty && echo "$line"'
```

**Comment by wesharper** [comment]
I can confirm that GitLab auth is no longer working on Mac as well. I recently updated to the latest version, but I don't know my previous version, so I can't pinpoint a release.

**Comment by Beautifulme8** [comment]
What's the new issue?

**Comment by dosolkowski-work** [comment]
Unfortunately this seems to have actually been an unusual GitLab outage; I think they have fixed it. The problem is resolved for me; I don't know if anyone else is still encountering the issues, but I believe the issue can be closed.
